### ISSUE TITLE
Tela de Cadastro e Desativação de Operador

### ISSUE THREAD

**Issue by Givs** [shykiu77/ticket-cine-frontend#9]
**Descrição**:
Criar uma tela onde o gerente possa cadastrar novos operadores no sistema, inserindo informações como CPF, nome e e-mail. A tela também permitirá que o gerente desative o cadastro de operadores existentes.

**Casos de Uso Relacionados:**
Adicionar cadastro de operador.
Desativar cadastro de operador.

**Tasks:**
 - [ ] UI: Criar formulário para o cadastro de operadores, com campos para cpf, nome, email.
 - [ ] UI: Exibir lista de operadores cadastrados com opção de desativação de cadastro.
 - [ ] Integração: Conectar à API de cadastro de operador e desativação de cadastro de operador.
